# Generated by Django 4.2.2 on 2023-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maybelline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('price', models.FloatField(null=True)),
                ('image_link', models.CharField(max_length=255, null=True)),
                ('product_link', models.CharField(max_length=255, null=True)),
                ('website_link', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('category', models.CharField(max_length=15, null=True)),
                ('product_type', models.CharField(max_length=20, null=True)),
                ('colour_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
